### ISSUE TITLE
All genes from the cell classifier model must be present in the dataset to perform classification

### ISSUE THREAD

**Issue by saifsikdar** [grisslab/scAnnotatR#10]
Hi,

I am seeing many warning signs that mention that all genes for each cell classifier model must be present in the dataset to perform classification. Is there any way to classify cells using fewer genes? 
The code I run is:

`seurat.obj <- classify_cells(classify_obj = immune, 
                             assay = 'RNA', slot = 'data',
                             cell_types = 'all', 
                             path_to_models = 'default')`
Output:
Warning: All genes from T cells classifier model must be present in the dataset to perform classification. Classification of T cells skipped.
Error in mat[, idx.chunk, drop = FALSE] : subscript out of bounds

I look forward to hearing your suggestion. Thank you!

**Comment by jgriss** [comment]
Hi @saifsikdar 

Sorry! We missed your question.

Is this still relevant for you?

**Comment by MarineSr** [comment]
Hi @jgriss, 
i have the same issue regarding the warning about missign genes. Is there a way to bypass it or to modify the scAnnotate objects ? 
Thanks a lot, 
Marine

**Comment by CarlyDeAntoneo** [comment]
hello, 

we're having the same issue here. Could it be due to the fact that our genes are read in a different case (IE CD19 versus Cd19)?

**Comment by jgriss** [comment]
Hi @vintagelego,

If your genes are in different cases, this generally points to a mouse genome?

Our models are only validated for human data. That's why this does not fit.

Kind regards,
Johannes
