### ISSUE TITLE
Error in AnnotationHub::AnnotationHub()

### ISSUE THREAD

**Issue by SudoSchrodinger** [grisslab/scAnnotatR#4]
Hi! Thanks for the package. 

When I run:
 Cell_types <- classify_cells(classify_obj = seurat.integrated,
                             assay = "RNA",
                             slot = "counts",
                             cell_types = "all",
                             path_to_models = "default")

**Appear this error message**

"DEFUNCT: As of AnnotationHub (>2.23.2), default caching location has changed"

Can you help me? 

Thanks,

**Comment by nttvy** [comment]
Hi @SudoSchrodinger 

Thank you for having been interested in our tool. 

We cannot reproduce your issue on our end. So we can only suggest some ideas that might work. First, can you check which version of AnnotationHub you are having? You may also update the package if it was of an old version. Secondly, we suggest trying the solution proposed by Bioconductor [here](https://bioconductor.org/packages/devel/bioc/vignettes/AnnotationHub/inst/doc/TroubleshootingTheCache.html) (5. Default Caching Location Update).

We hope these help.
Bests,
Vy
