### ISSUE TITLE
slot "marker_genes"

### ISSUE THREAD

**Issue by antoine4ucsd** [grisslab/scAnnotatR#7]
Hello
thank you for developing this package
I am trying to identify cell types from human brain samples using scAnnotatR. 
(some samples may be contaminated with blood so might be worth including immune cells)
if I ran this:
```
classify_cells(classify_obj = mydata, 
                             assay = 'RNA', slot = 'counts',
                             cell_types = 'T cells', 
                             path_to_models = 'default')
```
it works 
but if I want to retrieve all possible cells I get this error:

```
classify_cells(classify_obj = mydata, 
                             assay = 'RNA', slot = 'counts',
                             cell_types = 'T cells', 
                             path_to_models = 'default')
Error in marker_genes(x) : 
  trying to get slot "marker_genes" from an object of a basic class ("NULL") with no slots
```
any suggestions?
where can I find the list of available cell types?

thank you!

**Comment by jgriss** [comment]
Hi @antoine4ucsd ,

Thanks a lot for your interest in our package!

Just to be sure: The code you pasted is identical in the two boxes. Is that correct?

**Comment by antoine4ucsd** [comment]
Sorry. For the second one, I use cell types “all” and it failed

a

On Jan 10, 2023, at 11:32 AM, Johannes Griss ***@***.***> wrote:

﻿

Hi @antoine4ucsd<https://urldefense.com/v3/__https://github.com/antoine4ucsd__;!!LLK065n_VXAQ!jq5inF9_OSV9oaxuesC8WdyaMqeii-AYF10M0LklUpwE8bMneYFRWI-5QhU4w3QD8BCHDRWd7bDn6fAt1BdawPMtbp4$> ,

Thanks a lot for your interest in our package!

Just to be sure: The code you pasted is identical in the two boxes. Is that correct?

**Comment by antoine4ucsd** [comment]
see below

```
classify_cells(classify_obj = mydata, 
                                       assay = 'RNA', slot = 'counts',
                                       cell_types = 'all', 
                                       path_to_models = 'default')
snapshotDate(): 2022-10-31
loading from cache
Error in marker_genes(x) : 
  trying to get slot "marker_genes" from an object of a basic class ("NULL") with no slots
```

**Comment by nttvy** [comment]
@jgriss sorry for interrupting but I think I know the problem
@antoine4ucsd I think this [issue](https://github.com/grisslab/scAnnotatR/issues/5#issue) can be related to your question. In brief, your data may not contain the features/genes that are used by one/some pre-trained classifiers. To verify this, you can first access all our in-built models: 
```
default_models <- load_models("default")
names(default_models)
default_models
```
and you can also access the marker genes of the models, for example:
```
marker_genes(default_models[['B cells']])
```

Then you check whether any model(s) cannot be used on your data.

Please return to this issue if this doesn't work.
Hope this helps.
Vy

**Comment by antoine4ucsd** [comment]
thank you. I will try and get back to you

**Comment by jgriss** [comment]
Hi @nttvy 

Thanks a lot for the fast response!

Maybe we can think about whether we can improve the respective error message?

**Comment by nttvy** [comment]
Hi @jgriss 

3 solutions: 1/ first check the availability of all features used by models called by the user and raise an error, or 2/ also check the availability of the features but only raise a warning and continue applying the models having enough features, or 3/ check the availability of the features, raise a warning, and add zeros to unavailable features.

I can implement one of these solutions in a short period of time.

Vy

**Comment by jgriss** [comment]
Hi,

Personally, I believe that solution 2 is the best.

1) Possible but not so user friendly

2) User does get the warning but the function still works

3) We don't know what the outcome would be

Does this sound reasonable?

**Comment by nttvy** [comment]
Hi @jgriss 

I agree. I also made changes to the 'develop' branch. Please check this out.

Vy

**Comment by jgriss** [comment]
Hi @nttvy 

Changes look great! Thanks a lot!

I only adapted the version number and error message text. Please check if you're happy with them.

**Comment by nttvy** [comment]
Hi @jgriss 

Everything looks good. Thank you!

Vy

**Comment by seb951** [comment]
Thanks for the fix. Cases such as this one will still fail with a cryptic error message (I understand why, but perhaps we could have a more explicit error message  before you push changes to the main branch? 
```
seurat.obj <- classify_cells(classify_obj = tirosh_mel80_example, 
                              assay = 'RNA', slot = 'counts',
                              cell_types = c('Plasma cells'), 
                              path_to_models = 'default')
```

Also, in other cases it feels like a more explicit warning would help, such as:
`Warning: All genes from Plasma cells classifier model must be present in the dataset to perform classification. Classification of Plasma cells skipped.` 
instead of :
`Warning: Some genes to classify Plasma cells are not available in the dataset. Classification of Plasma cells skipped.`
Thank you.

**Comment by jgriss** [comment]
Hi @seb951 

Thanks a lot for the very helpful feedback! Error message is already updated.

We'll also try to catch the other cases
