### ISSUE TITLE
ambiguous cell types in train_classifier()

### ISSUE THREAD

**Issue by seb951** [grisslab/scAnnotatR#9]
Hi,

`train_classifier()` considers cell types containing "/", ",", "-", "+", ".", "and", "or", "(", ")", as "ambiguous" . Perhaps this is a fine default, but it would be nice if this was an argument one could set when calling `train_classifier()`. Otherwise we have to recode cell types which can be totally valid and unique in a dataset...

Thanks.

**Comment by jgriss** [comment]
Hi @seb951 ,

Thanks a lot for the feedback! I've created a patch already (see above). You can directly install the updated R package from our `develop` branch using `devtools`:

```R
devtools::install_github(grisslab/scAnnotatR[develop])
```

@nttvy If you are OK with the changes, I'd merge them into `main` and push to BioConductor.

**Comment by nttvy** [comment]
Hi @jgriss 

Perfect! Thanks a lot! I'm OK with the changes.
